/**
 * Events Definition
 * Rules: Define all app events, avoid magic strings
 */

export const EVENTS = {
  // Command Events (User actions -> Controller)
  COMMAND: {
    ADD_URL: 'COMMAND.ADD_URL',
    UPDATE_URL: 'COMMAND.UPDATE_URL',
    REMOVE_URL: 'COMMAND.REMOVE_URL',
    REANALYZE_URL: 'COMMAND.REANALYZE_URL',
    START_ANALYSIS: 'COMMAND.START_ANALYSIS',
    STOP_ANALYSIS: 'COMMAND.STOP_ANALYSIS',
    CLEAR_ALL: 'COMMAND.CLEAR_ALL',
    EXPORT_DATA: 'COMMAND.EXPORT_DATA',
    IMPORT_DATA: 'COMMAND.IMPORT_DATA',
    PARSE_SITEMAP: 'COMMAND.PARSE_SITEMAP',
    OPEN_REPORT: 'COMMAND.OPEN_REPORT',
    DOWNLOAD_REPORT: 'COMMAND.DOWNLOAD_REPORT',
    TOGGLE_PRO_MODE: 'COMMAND.TOGGLE_PRO_MODE',
    CREATE_SHARE: 'COMMAND.CREATE_SHARE'
  },

  // Domain Events (Data changes, DataEngine -> UI)
  DOMAIN: {
    URL_ADDED: 'DOMAIN.URL_ADDED',
    URL_REMOVED: 'DOMAIN.URL_REMOVED',
    URL_UPDATED: 'DOMAIN.URL_UPDATED',
    ANALYSIS_STARTED: 'DOMAIN.ANALYSIS_STARTED',
    ANALYSIS_COMPLETED: 'DOMAIN.ANALYSIS_COMPLETED',
    ANALYSIS_FAILED: 'DOMAIN.ANALYSIS_FAILED',
    ANALYSIS_RESET: 'DOMAIN.ANALYSIS_RESET',
    DATA_CLEARED: 'DOMAIN.DATA_CLEARED',
    DATA_IMPORTED: 'DOMAIN.DATA_IMPORTED',
    STATISTICS_UPDATED: 'DOMAIN.STATISTICS_UPDATED',
    CONFIG_UPDATED: 'DOMAIN.CONFIG_UPDATED'
  },

  // Process Events (Batch processing progress)
  PROCESS: {
    BATCH_STARTED: 'PROCESS.BATCH_STARTED',
    BATCH_PROGRESS: 'PROCESS.BATCH_PROGRESS',
    BATCH_COMPLETED: 'PROCESS.BATCH_COMPLETED',
    BATCH_ABORTED: 'PROCESS.BATCH_ABORTED',
    BATCH_PAUSED: 'PROCESS.BATCH_PAUSED'
  },

  // UI Events (UI layer internal)
  UI: {
    FILTER_CHANGED: 'UI.FILTER_CHANGED',
    DIALOG_OPENED: 'UI.DIALOG_OPENED',
    DIALOG_CLOSED: 'UI.DIALOG_CLOSED',
    CONFIRM_REQUESTED: 'UI.CONFIRM_REQUESTED',
    CONFIRM_RESOLVED: 'UI.CONFIRM_RESOLVED',
    UPDATE_BUTTON: 'UI.UPDATE_BUTTON',
    EDIT_URL_REQUESTED: 'UI.EDIT_URL_REQUESTED'
  },

  // System Events (System level)
  SYSTEM: {
    ERROR: 'SYSTEM.ERROR',
    ALERT_REQUESTED: 'SYSTEM.ALERT_REQUESTED',
    DOWNLOAD_REQUESTED: 'SYSTEM.DOWNLOAD_REQUESTED',
    PARSING_STARTED: 'SYSTEM.PARSING_STARTED',
    PARSING_ENDED: 'SYSTEM.PARSING_ENDED'
  },

  // App Events (Application level)
  APP_EVENTS: {
    SCROLL_STATE_CHANGED: 'APP_EVENTS.SCROLL_STATE_CHANGED'
  }
};
