name = "lazy-pagespeed-api"
main = "src/index.js"
compatibility_date = "2024-10-01"

[vars]
# API_KEY 需要透過 wrangler secret 設定
# wrangler secret put GOOGLE_API_KEY

[[r2_buckets]]
binding = "SHARE_BUCKET"
bucket_name = "lazy-pagespeed-reports"

[[kv_namespaces]]
binding = "SHARE_KV"
id = "88301ce71557419a9ac5ad22f6f921cc"
